

#server:
#  servlet:
#    context-path: /api/

springDoc:
  api-docs:
    enabled: true
    path: /api/api-docs
  swagger-ui:
    path: /api/swagger


spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true  # TLS를 사용하려면 true

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.sql: DEBUG
    org.hibernate.type: TRACE
    org.hibernate.type.descriptor.sql : trace

mail:
  sender1:
    username: email1@example.com
    password: your_password_for_email1
  sender2:
    username: email2@example.com
    password: your_password_for_email2
  sender3:
    username: email3@example.com
    password: your_password_for_email3
