

#server:
#  servlet:
#    context-path: /api/

springDoc:
  api-docs:
    enabled: true
    path: /api/api-docs
  swagger-ui:
    path: /api/swagger


spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/tinos
    username: root
    password: 1234
  mail:
    host: smtp.gmail.com
    port: 587
    username: tukorea.tino.project@gmail.com
    password: lghajqjvhcgmhtwa
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.sql: DEBUG
    org.hibernate.type: TRACE
    org.hibernate.type.descriptor.sql : trace
